name = "ahmadiya-survey-worker"
main = "worker.js"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ahmadiya-survey-media"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "72e8c72d56ed4cd587adb56393a4da75"

[vars]
R2_PUBLIC_BASE_URL = "https://pub-3fb0b86037554ed0b842bc258e8a3051.r2.dev"
FIREBASE_DB_URL = "https://YOUR_PROJECT-default-rtdb.firebaseio.com"